id: P010675
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:19:22.975997
source_metadata:
  id: bdr:W23943
  title: རླུང་སེམས་དབྱེར་མེད་ཀྱི་ཁྲིད་ཡིག
  author: ''
  volumes:
    2c335d0dc49144f89bc70b32451ef377:
      image_group_id: I3583
      title: ''
      volume_number: 1
      total_pages: 636
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
