id: P010675
initial_creation_type: ocr
source_metadata:
  id: bdr:W23943
  title: རླུང་སེམས་དབྱེར་མེད་ཀྱི་ཁྲིད་ཡིག
  author: ''
  volumes:
    2c335d0dc49144f89bc70b32451ef377:
      image_group_id: I3583
      title: ''
      volume_number: 1
      total_pages: 636
