id: I494287B4
legacy_id: P010675
ocr_import_info:
  bdrc_scan_id: W23943
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T05:39:29'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:20:27.041834+00:00'
last_modified: 2022-09-02 13:21:08.408379
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23943
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23943
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རླུང་སེམས་དབྱེར་མེད་ཀྱི་ཁྲིད་ཡིག
  author: ཀརྨ་པ ༠༨་མི་བསྐྱོད་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.7471394978198608
  ocr_word_median_confidence_index: 0.8399999737739563
quality: null
bases:
  I3583:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3583
      total_pages: 636
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3583.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7471394978198608
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
